language: node_js
node_js:
  - "8"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
before_script:
  - sleep 15
script:
  - npm run react-dev
  - npm run server-dev